### ISSUE TITLE
Generate frozen versions of the files

### ISSUE THREAD

**Issue by luispedro** [BigDataBiology/Duan2023__GMSCv1_Construction_And_Analysis#11]
Eventually for public use, but first internal-only

- [x] FASTA files (FNA & FAA)
- [x] Family mapping files
- [x] Taxonomic annotation (see #9)
- [x] Origin (habitat—microontology, see #10)
- [ ] Quality assignments (see #3)
- [x] Comprehensive `README` file (maybe other documentation)
